### ISSUE TITLE
Can I use your code with different dataset .

### ISSUE THREAD

**Issue by beebrain** [amithmkini/fooling-dnn#3]
Hi, thank you for your example code, it awesome.
I have some question, I have a plan to create my owner fooling image with my dataset.
Can I use your code to create that?

**Comment by amithmkini** [comment]
Yes, you can. It has a MIT license, so you can use it for any other purposes without any restrictions. I had designed this for a dataset with smaller images (something like MNIST or CIFAR-10), but you can try on your own dataset.

**Comment by beebrain** [comment]
Thank you so much.
I executed your code, it created a directly encoded fooling image. Could you suggest me to create an indirectly encoded fooling image?
i found that in this video  
https://m.youtube.com/watch?v=M2IebCN9Ht4&time_continue=156&ebc=ANyPxKp8mF3NRnGAgHypN6JwCudhD21eZ_Jevgvpb4rDrdLcuj3HoOvCLHyJL1rtxkltMrs5pR65YdTN1sej1yNC6FiWKH4qUA

from this website 
http://www.evolvingai.org/fooling

Thank you in advance.

**Comment by amithmkini** [comment]
Indirectly encoded are not done by this code. Sorry. Closing this issue.
